import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import '../data/repositories/auth_repository.dart';
import '../data/repositories/event_repository.dart';
import '../data/repositories/orders_repository.dart';
import '../data/repositories/product_repository.dart';
import '../data/repositories/sales_repository.dart';
import '../data/repositories/settings_repository.dart';
import '../models/order.dart';
import '../models/sale.dart';

class _ProductInfo {
  const _ProductInfo({
    required this.id,
    required this.name,
    required this.basePrice,
    required this.colorIdByValue,
    required this.sizeIdByValue,
  });

  final int id;
  final String name;
  final double basePrice;
  final Map<String, int> colorIdByValue;
  final Map<String, int> sizeIdByValue;
}

/// Loads `assets/dev/mock_data.json` (generated by `tool/generate_mock_data.py`)
/// and seeds companies, products, bazaar events, and sales through the real
/// repository APIs, so business rules (stock reservation, etc.) are honored
/// exactly as they would be from the UI. Debug/dev builds only — see
/// [SyncBazaarApp] for the `kDebugMode` gate.
class DevMockDataSeeder {
  DevMockDataSeeder({
    required this.eventRepository,
    required this.productRepository,
    required this.salesRepository,
    required this.ordersRepository,
    required this.settingsRepository,
    required this.authRepository,
  });

  final EventRepository eventRepository;
  final ProductRepository productRepository;
  final SalesRepository salesRepository;
  final OrdersRepository ordersRepository;
  final SettingsRepository settingsRepository;
  final AuthRepository authRepository;

  Future<void> seed() async {
    final Map<String, dynamic> data;
    try {
      final raw = await rootBundle.loadString('assets/dev/mock_data.json');
      data = jsonDecode(raw) as Map<String, dynamic>;
    } catch (_) {
      return;
    }

    try {
      final users = await authRepository.listUsers();
      final userIdByEmail = {
        for (final user in users) user.email.toLowerCase(): user.id,
      };

      final companyIdByTempId = await _seedCompanies(
        (data['companies'] as List<dynamic>? ?? const [])
            .cast<Map<String, dynamic>>(),
      );
      final productByTempId = await _seedProducts(
        (data['products'] as List<dynamic>? ?? const [])
            .cast<Map<String, dynamic>>(),
      );
      final rawEvents = (data['events'] as List<dynamic>? ?? const [])
          .cast<Map<String, dynamic>>();
      final eventIdByTempId = await _seedEvents(
        rawEvents,
        companyIdByTempId,
        productByTempId,
        userIdByEmail,
      );
      await _seedSales(
        (data['sales'] as List<dynamic>? ?? const [])
            .cast<Map<String, dynamic>>(),
        rawEvents,
        eventIdByTempId,
        productByTempId,
        userIdByEmail,
      );
    } catch (error, stackTrace) {
      debugPrint('DevMockDataSeeder failed: $error\n$stackTrace');
    }
  }

  Future<Map<String, int>> _seedCompanies(
    List<Map<String, dynamic>> raw,
  ) async {
    final map = <String, int>{};
    for (final item in raw) {
      final company = await settingsRepository.createCompany(
        name: item['name'] as String,
        address: item['address'] as String? ?? '',
        contact: item['contact'] as String? ?? '',
        incentivePercent: (item['incentive_percent'] as num?)?.toDouble() ?? 0,
        bufferPercent: (item['buffer_percent'] as num?)?.toDouble() ?? 0,
      );
      map[item['id'] as String] = company.id;
    }
    return map;
  }

  Future<Map<String, _ProductInfo>> _seedProducts(
    List<Map<String, dynamic>> raw,
  ) async {
    final result = <String, _ProductInfo>{};

    for (final item in raw) {
      final colors = (item['colors'] as List<dynamic>).cast<String>();
      final sizes = (item['sizes'] as List<dynamic>).cast<String>();
      final stockEntries = (item['stock'] as List<dynamic>)
          .cast<Map<String, dynamic>>();

      final combinationStocks = <String, int>{
        for (final entry in stockEntries)
          ProductRepository.combinationValueKey(
            entry['color'] as String,
            entry['size'] as String,
          ): (entry['qty'] as num)
              .toInt(),
      };

      final product = await productRepository.saveProduct(
        name: item['name'] as String,
        // Bundled asset path, e.g. assets/images/default_shoes/sambaog.png.
        // ProductThumbnail resolves a non-http path through Image.asset, so
        // seeded products render a real photo with no extra plumbing.
        imagePath: item['image'] as String?,
        basePrice: (item['base_price'] as num).toDouble(),
        variantGroups: [
          VariantCategoryDraft(name: 'Color', optionValues: colors),
          VariantCategoryDraft(name: 'Size', optionValues: sizes),
        ],
        combinationStocks: combinationStocks,
      );

      final groups = await productRepository.variantGroupsForProduct(
        product.id,
      );
      if (groups.length < 2) {
        continue;
      }
      final colorOptions = await productRepository.variantOptionsForGroup(
        groups[0].id,
      );
      final sizeOptions = await productRepository.variantOptionsForGroup(
        groups[1].id,
      );

      result[item['id'] as String] = _ProductInfo(
        id: product.id,
        name: product.name,
        basePrice: product.basePrice,
        colorIdByValue: {for (final o in colorOptions) o.value: o.id},
        sizeIdByValue: {for (final o in sizeOptions) o.value: o.id},
      );
    }
    return result;
  }

  Future<Map<String, int>> _seedEvents(
    List<Map<String, dynamic>> raw,
    Map<String, int> companyIdByTempId,
    Map<String, _ProductInfo> productByTempId,
    Map<String, int> userIdByEmail,
  ) async {
    final map = <String, int>{};
    for (final item in raw) {
      final companyId = companyIdByTempId[item['company_id'] as String];
      if (companyId == null) {
        continue;
      }

      final allocationsRaw = (item['allocations'] as List<dynamic>? ?? const [])
          .cast<Map<String, dynamic>>();
      final allocations = <String, int>{};
      for (final alloc in allocationsRaw) {
        final product = productByTempId[alloc['product_id'] as String];
        if (product == null) {
          continue;
        }
        final colorId = product.colorIdByValue[alloc['color'] as String];
        final sizeId = product.sizeIdByValue[alloc['size'] as String];
        if (colorId == null || sizeId == null) {
          continue;
        }
        final key = productRepository.allocationKey(
          product.id,
          optionIdA: colorId,
          optionIdB: sizeId,
        );
        allocations[key] = (alloc['qty'] as num).toInt();
      }

      if (allocations.isNotEmpty) {
        await productRepository.reserveStocksByAllocationKey(allocations);
      }

      final event = await eventRepository.createEvent(
        name: item['name'] as String,
        companyId: companyId,
        startDate: DateTime.parse(item['start_date'] as String),
        endDate: DateTime.parse(item['end_date'] as String),
        acceptedPaymentMethods:
            (item['payment_methods'] as List<dynamic>? ?? const ['CASH'])
                .cast<String>(),
        allocationsByAllocationKey: allocations,
      );
      map[item['id'] as String] = event.id;

      final employeeEmails =
          (item['assigned_employee_emails'] as List<dynamic>? ?? const [])
              .cast<String>();
      final employeeIds = employeeEmails
          .map((email) => userIdByEmail[email.toLowerCase()])
          .whereType<int>()
          .toList();
      if (employeeIds.isNotEmpty) {
        await authRepository.assignEmployeesToBazaar(
          eventId: event.id,
          employeeIds: employeeIds,
        );
      }
    }
    return map;
  }

  Future<void> _seedSales(
    List<Map<String, dynamic>> raw,
    List<Map<String, dynamic>> rawEvents,
    Map<String, int> eventIdByTempId,
    Map<String, _ProductInfo> productByTempId,
    Map<String, int> userIdByEmail,
  ) async {
    final eventStartByTempId = {
      for (final event in rawEvents)
        event['id'] as String: DateTime.parse(event['start_date'] as String),
    };
    final employeeEmailsByEventTempId = {
      for (final event in rawEvents)
        event['id'] as String:
            (event['assigned_employee_emails'] as List<dynamic>? ?? const [])
                .cast<String>(),
    };

    var idCounter = 900000000;
    for (final item in raw) {
      final eventTempId = item['event_id'] as String;
      final eventId = eventIdByTempId[eventTempId];
      final product = productByTempId[item['product_id'] as String];
      if (eventId == null || product == null) {
        continue;
      }

      final colorId = product.colorIdByValue[item['color'] as String];
      final sizeId = product.sizeIdByValue[item['size'] as String];
      final qty = (item['qty'] as num).toInt();

      final reserved = await productRepository.reserveForSale(
        productId: product.id,
        optionIdA: colorId,
        optionIdB: sizeId,
        quantity: qty,
      );
      if (!reserved) {
        continue;
      }

      final discountPercent = (item['discount_percent'] as num?)?.toInt() ?? 0;
      final total = product.basePrice * qty * (1 - discountPercent / 100);

      final eventStart = eventStartByTempId[eventTempId] ?? DateTime.now();
      final dayOffset = (item['days_after_start'] as num?)?.toInt() ?? 0;
      final timestamp = eventStart.add(
        Duration(
          days: dayOffset,
          hours: 9 + (idCounter % 8),
          minutes: (idCounter * 7) % 60,
        ),
      );

      final saleId = idCounter++;
      final sale = Sale(
        id: saleId,
        // Derived from the row's own id rather than random, so re-seeding
        // produces the same uuids. Seeded sales are already on the "server" as
        // far as this dataset is concerned; a fresh uuid each launch would make
        // every restart look like a new batch to upload.
        clientUuid: 'seed-sale-${saleId.toString().padLeft(6, '0')}',
        eventId: eventId,
        productId: product.id,
        variantOptionIdA: colorId,
        variantOptionIdB: sizeId,
        customerName: item['customer_name'] as String? ?? 'Walk-in',
        employeeId: '',
        paymentMethod: item['payment_method'] as String? ?? 'CASH',
        qty: qty,
        total: total,
        timestamp: timestamp,
        orderStatus: OrderStatus.completed,
        synced: false,
      );
      await salesRepository.addSale(sale);

      final employeeEmails =
          employeeEmailsByEventTempId[eventTempId] ?? const [];
      final userId = employeeEmails.isNotEmpty
          ? (userIdByEmail[employeeEmails.first.toLowerCase()] ?? 1)
          : 1;

      final variantParts = <String>[
        if (item['color'] != null) 'Color ${item['color']}',
        if (item['size'] != null) 'Size ${item['size']}',
      ];
      final productLabel = variantParts.isEmpty
          ? product.name
          : '${product.name} (${variantParts.join(', ')})';

      await ordersRepository.addOrder(
        Order(
          id: saleId + 500000000,
          saleId: saleId,
          eventId: eventId,
          customerName: sale.customerName,
          productLabel: productLabel,
          orderStatus: OrderStatus.completed,
          userId: userId,
          paymentMethod: sale.paymentMethod,
          updatedAt: timestamp,
          synced: false,
        ),
      );
    }
  }
}
